"""baseline schema matching production

Revision ID: f9e59a180957
Revises: 
Create Date: 2026-05-01 21:01:39.438276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e59a180957'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('layout_json', sa.Text(), nullable=False),
    sa.Column('widgets_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_layouts_user_id'), 'dashboard_layouts', ['user_id'], unique=True)
    op.create_table('dashboard_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('widget_id', sa.String(length=100), nullable=False),
    sa.Column('blob_name', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dashboard_media_widget', 'dashboard_media', ['widget_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_dashboard_media_widget_id'), 'dashboard_media', ['widget_id'], unique=False)
    op.create_table('insights',
    sa.Column('insight_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('entity_label', sa.String(length=200), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('baseline', sa.Text(), nullable=False),
    sa.Column('deviation_score', sa.Integer(), nullable=False),
    sa.Column('deviation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('recommended_actions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_signals', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('acted_on_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('insight_id')
    )
    op.create_index('ix_insights_created', 'insights', ['created_at'], unique=False)
    op.create_index('ix_insights_domain_entity', 'insights', ['domain', 'entity_id', 'status'], unique=False)
    op.create_table('options_chain_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=False),
    sa.Column('chain_json', sa.Text(), nullable=False),
    sa.Column('contract_count', sa.Integer(), nullable=False),
    sa.Column('dte_min', sa.Integer(), nullable=True),
    sa.Column('dte_max', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('snapshot_id'),
    sa.UniqueConstraint('symbol', 'snapshot_date', name='uq_chain_snapshot_symbol_date')
    )
    op.create_index(op.f('ix_options_chain_snapshots_snapshot_date'), 'options_chain_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_options_chain_snapshots_symbol'), 'options_chain_snapshots', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_key', sa.String(length=50), nullable=False),
    sa.Column('trade_structure', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('entry_greeks', sa.Text(), nullable=True),
    sa.Column('entry_iv_rank', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('entry_sma_alignment', sa.Text(), nullable=True),
    sa.Column('entry_underlying_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('claude_probability_matrix', sa.Text(), nullable=True),
    sa.Column('claude_exit_levels', sa.Text(), nullable=True),
    sa.Column('claude_verdict', sa.Text(), nullable=True),
    sa.Column('claude_score', sa.Integer(), nullable=True),
    sa.Column('health_grade', sa.String(length=2), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('current_pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('last_monitored_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('outcome_pnl', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index('ix_positions_user_status', 'positions', ['user_id', 'status'], unique=False)
    op.create_index('ix_positions_user_symbol', 'positions', ['user_id', 'symbol'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_key', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index('ix_strategy_configs_user_key', 'strategy_configs', ['user_id', 'strategy_key'], unique=False)
    op.create_table('symbol_context',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('context_id')
    )
    op.create_index('ix_symbol_context_lookup', 'symbol_context', ['symbol', 'source_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_symbol_context_symbol'), 'symbol_context', ['symbol'], unique=False)
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=300), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('trade_data', sa.JSON(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_id', name='uq_user_favorites_trade')
    )
    op.create_index('ix_user_favorites_user', 'user_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('csrf_token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_table('user_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_watchlist_symbol')
    )
    op.create_index(op.f('ix_user_watchlist_user_id'), 'user_watchlist', ['user_id'], unique=False)
    op.create_index('ix_user_watchlist_user_pos', 'user_watchlist', ['user_id', 'position'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=True),
    sa.Column('market_data_provider', sa.String(length=50), nullable=True),
    sa.Column('account_provider', sa.String(length=50), nullable=True),
    sa.Column('trading_provider', sa.String(length=50), nullable=True),
    sa.Column('trading_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('validation_assessments',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('jira_ticket', sa.String(length=20), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('tab', sa.String(length=20), nullable=False),
    sa.Column('strike', sa.String(length=20), nullable=False),
    sa.Column('expiration', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('agreement', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index('ix_validation_assessments_ticker', 'validation_assessments', ['ticker'], unique=False)
    op.create_index('ix_validation_assessments_ticket', 'validation_assessments', ['jira_ticket'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watchlists_user', 'watchlists', ['user_id'], unique=False)
    op.create_table('agent_run_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('trade_key', sa.String(length=255), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_system', sa.Text(), nullable=True),
    sa.Column('prompt_user', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('market_snapshot', sa.JSON(), nullable=True),
    sa.Column('trade_snapshot', sa.JSON(), nullable=True),
    sa.Column('model_response_raw', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=True),
    sa.Column('otel_trace_id', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_run_log_run_id', 'agent_run_log', ['run_id'], unique=False)
    op.create_index('ix_agent_run_log_trade_key', 'agent_run_log', ['trade_key'], unique=False)
    op.create_index('ix_agent_run_log_user', 'agent_run_log', ['user_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_user_event', 'audit_log', ['user_id', 'event_type'], unique=False)
    op.create_table('option_chain_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('contract_count', sa.Integer(), nullable=True),
    sa.Column('chain_data', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_chain_snapshots_symbol_time', 'option_chain_snapshots', ['symbol', 'captured_at'], unique=False)
    op.create_index(op.f('ix_option_chain_snapshots_user_id'), 'option_chain_snapshots', ['user_id'], unique=False)
    op.create_index('ix_option_chain_snapshots_user_symbol', 'option_chain_snapshots', ['user_id', 'symbol', 'captured_at'], unique=False)
    op.create_table('position_assessments',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('synopsis', sa.String(length=200), nullable=True),
    sa.Column('claude_read', sa.Text(), nullable=False),
    sa.Column('exit_levels', sa.Text(), nullable=True),
    sa.Column('market_snapshot', sa.Text(), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.position_id'], ),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index('ix_position_assessments_position', 'position_assessments', ['position_id', 'created_at'], unique=False)
    op.create_table('schwab_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('refresh_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schwab_tokens_user', 'schwab_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_schwab_tokens_user_id'), 'schwab_tokens', ['user_id'], unique=True)
    op.create_table('symbol_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_symbol_quotes_symbol_time', 'symbol_quotes', ['symbol', 'captured_at'], unique=False)
    op.create_index(op.f('ix_symbol_quotes_user_id'), 'symbol_quotes', ['user_id'], unique=False)
    op.create_index('ix_symbol_quotes_user_symbol_time', 'symbol_quotes', ['user_id', 'symbol', 'captured_at'], unique=False)
    op.create_table('trade_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('legs', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('net_debit', sa.Float(), nullable=True),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('breakeven', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('mfa_challenge_used', sa.Boolean(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_log_user_date', 'trade_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_trade_log_user_id'), 'trade_log', ['user_id'], unique=False)
    op.create_table('trade_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('trade_key', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('spread_label', sa.String(length=100), nullable=False),
    sa.Column('expiration', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=False),
    sa.Column('market_snapshot', sa.JSON(), nullable=False),
    sa.Column('trade_snapshot', sa.JSON(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'trade_key', name='uq_trade_recommendations_user_key')
    )
    op.create_index(op.f('ix_trade_recommendations_trade_key'), 'trade_recommendations', ['trade_key'], unique=False)
    op.create_index(op.f('ix_trade_recommendations_user_id'), 'trade_recommendations', ['user_id'], unique=False)
    op.create_index('ix_trade_recommendations_user_symbol', 'trade_recommendations', ['user_id', 'symbol'], unique=False)
    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('default_symbol', sa.String(length=10), nullable=True),
    sa.Column('min_dte', sa.Integer(), nullable=True),
    sa.Column('max_dte', sa.Integer(), nullable=True),
    sa.Column('strike_range_pct', sa.Float(), nullable=True),
    sa.Column('min_open_interest', sa.Integer(), nullable=True),
    sa.Column('min_volume', sa.Integer(), nullable=True),
    sa.Column('min_spread_width', sa.Float(), nullable=True),
    sa.Column('max_spread_width', sa.Float(), nullable=True),
    sa.Column('weight_expected_value', sa.Float(), nullable=True),
    sa.Column('weight_reward_risk', sa.Float(), nullable=True),
    sa.Column('weight_probability', sa.Float(), nullable=True),
    sa.Column('weight_liquidity', sa.Float(), nullable=True),
    sa.Column('max_risk_per_trade', sa.Float(), nullable=True),
    sa.Column('profit_target_pct', sa.Float(), nullable=True),
    sa.Column('stop_loss_pct', sa.Float(), nullable=True),
    sa.Column('extra_settings', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('watchlist_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watchlist_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_symbol')
    )
    op.create_index('ix_watchlist_symbols_watchlist', 'watchlist_symbols', ['watchlist_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('analysis_type', sa.String(length=20), nullable=False),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('chain_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('filter_params', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('total_valid', sa.Integer(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chain_snapshot_id'], ['option_chain_snapshots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_runs_symbol_time', 'analysis_runs', ['symbol', 'ran_at'], unique=False)
    op.create_index(op.f('ix_analysis_runs_user_id'), 'analysis_runs', ['user_id'], unique=False)
    op.create_index('ix_analysis_runs_user_symbol', 'analysis_runs', ['user_id', 'symbol', 'ran_at'], unique=False)
    op.create_table('analyzed_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('analysis_type', sa.String(length=20), nullable=False),
    sa.Column('spread_type', sa.String(length=20), nullable=True),
    sa.Column('long_strike', sa.Float(), nullable=True),
    sa.Column('short_strike', sa.Float(), nullable=True),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('expiration', sa.String(length=20), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('net_debit', sa.Float(), nullable=True),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('breakeven', sa.Float(), nullable=True),
    sa.Column('rr_ratio', sa.Float(), nullable=True),
    sa.Column('prob_of_profit', sa.Float(), nullable=True),
    sa.Column('ev_raw', sa.Float(), nullable=True),
    sa.Column('premium_dollars', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('theta_per_day', sa.Float(), nullable=True),
    sa.Column('iv', sa.Float(), nullable=True),
    sa.Column('long_volume', sa.Integer(), nullable=True),
    sa.Column('short_volume', sa.Integer(), nullable=True),
    sa.Column('long_oi', sa.Integer(), nullable=True),
    sa.Column('short_oi', sa.Integer(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analyzed_trades_run', 'analyzed_trades', ['run_id'], unique=False)
    op.create_index(op.f('ix_analyzed_trades_run_id'), 'analyzed_trades', ['run_id'], unique=False)
    op.create_index('ix_analyzed_trades_symbol_expiry', 'analyzed_trades', ['symbol', 'expiration'], unique=False)
    op.create_index(op.f('ix_analyzed_trades_user_id'), 'analyzed_trades', ['user_id'], unique=False)
    op.create_index('ix_analyzed_trades_user_symbol', 'analyzed_trades', ['user_id', 'symbol', 'captured_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyzed_trades_user_symbol', table_name='analyzed_trades')
    op.drop_index(op.f('ix_analyzed_trades_user_id'), table_name='analyzed_trades')
    op.drop_index('ix_analyzed_trades_symbol_expiry', table_name='analyzed_trades')
    op.drop_index(op.f('ix_analyzed_trades_run_id'), table_name='analyzed_trades')
    op.drop_index('ix_analyzed_trades_run', table_name='analyzed_trades')
    op.drop_table('analyzed_trades')
    op.drop_index('ix_analysis_runs_user_symbol', table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_user_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_runs_symbol_time', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index('ix_watchlist_symbols_watchlist', table_name='watchlist_symbols')
    op.drop_table('watchlist_symbols')
    op.drop_table('user_configs')
    op.drop_index('ix_trade_recommendations_user_symbol', table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_user_id'), table_name='trade_recommendations')
    op.drop_index(op.f('ix_trade_recommendations_trade_key'), table_name='trade_recommendations')
    op.drop_table('trade_recommendations')
    op.drop_index(op.f('ix_trade_log_user_id'), table_name='trade_log')
    op.drop_index('ix_trade_log_user_date', table_name='trade_log')
    op.drop_table('trade_log')
    op.drop_index('ix_symbol_quotes_user_symbol_time', table_name='symbol_quotes')
    op.drop_index(op.f('ix_symbol_quotes_user_id'), table_name='symbol_quotes')
    op.drop_index('ix_symbol_quotes_symbol_time', table_name='symbol_quotes')
    op.drop_table('symbol_quotes')
    op.drop_index(op.f('ix_schwab_tokens_user_id'), table_name='schwab_tokens')
    op.drop_index('ix_schwab_tokens_user', table_name='schwab_tokens')
    op.drop_table('schwab_tokens')
    op.drop_index('ix_position_assessments_position', table_name='position_assessments')
    op.drop_table('position_assessments')
    op.drop_index('ix_option_chain_snapshots_user_symbol', table_name='option_chain_snapshots')
    op.drop_index(op.f('ix_option_chain_snapshots_user_id'), table_name='option_chain_snapshots')
    op.drop_index('ix_option_chain_snapshots_symbol_time', table_name='option_chain_snapshots')
    op.drop_table('option_chain_snapshots')
    op.drop_index('ix_audit_log_user_event', table_name='audit_log')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_agent_run_log_user', table_name='agent_run_log')
    op.drop_index('ix_agent_run_log_trade_key', table_name='agent_run_log')
    op.drop_index('ix_agent_run_log_run_id', table_name='agent_run_log')
    op.drop_table('agent_run_log')
    op.drop_index('ix_watchlists_user', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_validation_assessments_ticket', table_name='validation_assessments')
    op.drop_index('ix_validation_assessments_ticker', table_name='validation_assessments')
    op.drop_table('validation_assessments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_user_watchlist_user_pos', table_name='user_watchlist')
    op.drop_index(op.f('ix_user_watchlist_user_id'), table_name='user_watchlist')
    op.drop_table('user_watchlist')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index('ix_user_favorites_user', table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_index(op.f('ix_symbol_context_symbol'), table_name='symbol_context')
    op.drop_index('ix_symbol_context_lookup', table_name='symbol_context')
    op.drop_table('symbol_context')
    op.drop_index('ix_strategy_configs_user_key', table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index('ix_positions_user_symbol', table_name='positions')
    op.drop_index('ix_positions_user_status', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_options_chain_snapshots_symbol'), table_name='options_chain_snapshots')
    op.drop_index(op.f('ix_options_chain_snapshots_snapshot_date'), table_name='options_chain_snapshots')
    op.drop_table('options_chain_snapshots')
    op.drop_index('ix_insights_domain_entity', table_name='insights')
    op.drop_index('ix_insights_created', table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_dashboard_media_widget_id'), table_name='dashboard_media')
    op.drop_index('ix_dashboard_media_widget', table_name='dashboard_media')
    op.drop_table('dashboard_media')
    op.drop_index(op.f('ix_dashboard_layouts_user_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    # ### end Alembic commands ###
